-- Generated with npm run seed:sql. No sample votes.
insert into public.questions(id,choices) values
('v2-empty-01',array['A','B','C','D']),
('v2-handrail-02',array['A','B','C','D']),
('v2-distance-03',array['A','B','D','E']),
('v2-entrance-04',array['A','B','D','E']),
('v2-partition-05',array['A','C','D']),
('v4-sinks-wet-06',array['A','B','C','D']),
('v4-sinks-broken-07',array['A','C','E']),
('v2-opposite-08',array['B','C','D','E','F']),
('v2-occupied-09',array['B','C','D']),
('v4-sinks-mixed-10',array['A','C','E']),
('v4-sinks-left-11',array['A','C']),
('v4-sinks-right-12',array['A','C']),
('v3-ends-13',array['B','C','D']),
('v4-sinks-busy-14',array['B','D']),
('v3-six-15',array['B','D','E','F']),
('v3-six-busy-16',array['B','E']),
('v3-eight-17',array['C','D','E','F','G','H']),
('v3-eight-split-18',array['C','D','E','F']),
('v3-eight-three-19',array['B','F','H']),
('v3-eight-two-20',array['B','G']),
('v3-ten-empty-21',array['A','B','C','D','E','F','G','H','I','J']),
('v3-ten-two-22',array['A','B','D','E','F','G','I','J']),
('v3-ten-four-23',array['B','C','D','G','H','I']),
('v3-ten-six-24',array['B','D','G','I']),
('v3-ten-eight-25',array['C','H']),
('v3-ten-wet-26',array['F','G','H','I','J']),
('v3-ten-rail-27',array['A','B','C','F','G','J']),
('v3-nine-28',array['A','C','E','F','H','I']),
('v3-seven-29',array['C','D','E']),
('v3-finale-30',array['B','G','J'])
on conflict(id) do nothing;
